places_to_visit = ['Reykjavic', 'Thailand', 'Bali', 'Miami', 'Japan']
print(places_to_visit)
print(sorted(places_to_visit))
print(places_to_visit)
print(sorted(places_to_visit, reverse=True))
print(places_to_visit)
places_to_visit.reverse()
print()
print(places_to_visit)
places_to_visit.reverse()
print(places_to_visit)
print()
places_to_visit.sort()
print(places_to_visit)
places_to_visit.sort(reverse=True)
print(places_to_visit)